ignore:
  - OtherLoader
  - WurstMod
  - TakeAndHoldTweaker
  - OpenScripts
  - MagazinePatcher
plugins:
  h3vr.otherloader.deli:
    guid: h3vr.otherloader
    version: 1.0.0
    loaders:
      item: item
      item_unordered: item_unordered
      item_last: item_last
