on:
  push:
    paths-ignore:
      - '.vscode/**/*'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Deliter.sln.DotSettings'
  pull_request:
    paths-ignore:
      - '.vscode/**/*'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Deliter.sln.DotSettings'

jobs:
  any:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build -c Release

      - name: Pack
        run: thunderstore/pack.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Thunderstore
          path: thunderstore/out/*
